### ISSUE TITLE
Curious about license

### ISSUE THREAD

**Issue by rowanlinux** [jakethakur/civdrafter#2]
Hello!

I like this project and I am interested in forking this to add civs from a modpack. I just wanted to ask what license you have shared this code under or if you are cool with my forking it publicly. 

Thanks for your time.

**Comment by jakethakur** [comment]
Heya!

Thanks for your interest! Feel free to fork it publicly. It was just a small project so it doesn't have a particular license currently - happy to add a non-restrictive one if you'd like.
